import type { ToolAction } from "../schemas/toolAction.js";
import type { NichePack } from "../nextStepController.js";

// Раздел 12.2, 15, ТЗ v3.0. ЭТО КЛЮЧЕВОЙ ИНТЕРФЕЙС ДЛЯ ПЕРЕХОДА ОТ ЭТАПА 0 К ЭТАПУ 1.
//
// Этап 0 (этот код) тестируется на MockExtractionProvider — детерминированном
// заглушечном провайдере с зафиксированными фикстурами, чтобы golden test не зависел
// от сети, ключей и недетерминизма реальной модели.
//
// Этап 1: команда пишет ClaudeExtractionProvider, который реализует этот же интерфейс,
// вызывая Anthropic API с tool use (раздел 13, 16 ТЗ — structured output вместо
// свободного JSON). Orchestrator (orchestrator.ts) НЕ МЕНЯЕТСЯ при этой замене —
// это и есть смысл интерфейса: подмена реализации, а не догадка о форме данных.
export interface ExtractionContext {
  tenant_id: string;
  businessFoundation: Record<string, unknown>;
  productCatalog: Record<string, unknown>[];
  /** Service line currently being built — model must not switch to another card until this one is complete. */
  activeServiceLine?: string;
  activeFactId?: string;
  /** Current onboarding stage (раздел 7.1.1 ТЗ v9.0). */
  assistant_stage?: 'profile_setup' | 'daily_assistant';
  /** Fields still missing from the best product card — passed so the model knows what to ask next. */
  missing_fields?: string[];
  /**
   * True when BusinessFoundation has company_description + market_type + geography (раздел 7.1.2 ТЗ v9.1).
   * When false the model MUST collect foundation data first; upsert_product_card is blocked by the validator.
   */
  foundationComplete?: boolean;
  /** Resolved niche pack for this tenant — used to show relevant examples in prompts (раздел 6 ТЗ v9.1). */
  nichePack?: NichePack;
}

export interface ExtractionResult {
  intent: string;
  confidence: number;
  proposed_actions: ToolAction[];
  next_step?: { id: string; question: string };
  /** Contextual reply when proposed_actions is empty — generated by the model, NOT a hardcoded fallback. */
  clarification_text?: string;
}

export interface ExtractionProvider {
  extract(userMessage: string, context: ExtractionContext): Promise<ExtractionResult>;
}
